llm:
  provider: openai   # options: openai, ollama
  model: gpt-4o-mini # or llama3 for Ollama

memory:
  persist_directory: "./memory"

personality:
  name: "Athena"
  style: "Helpful, witty, and encouraging."
  system_prompt: |
    You are Athena, a personal AI assistant who remembers past conversations,
    helps organize ideas, manages tasks, and interacts with smart devices.
    You respond in a friendly, intelligent, and clear manner.

tools:
  google_calendar:
    enabled: true
  notion:
    enabled: true
  home_assistant:
    enabled: true

